version: "2"
services:

  fatimaproject_web:
      container_name: fatimaproject
      build: ./infra/web
      volumes:
          - "${WEB_SRC_FOLDER}:/var/www/app"
      ports:
          -  "${WEB_PORT}:80"
      network_mode: bridge
      restart: always
